version: '2.3'
services:
  worker:
    image: myoung34/github-runner:latest
    environment:
      REPO_URL: https://github.com/motifdot
      RUNNER_NAME: prod-motif
      RUNNER_TOKEN: ************************
      RUNNER_WORKDIR: /opt/runner/work
      RUNNER_SCOPE: 'repo'
      LABELS: linux,x64,prod-motif
    security_opt:
      - label:disable
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/opt/runner:/opt/runner'
